fix: github actions syntax 수정

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -5,19 +5,25 @@ jobs:
     name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
-      - name: Use Node.js 12.x
+      - name: Checkout source code
+        uses: actions/checkout@v3
+
+      - name: Use Node.js 17.3.1
         uses: actions/setup-node@v1
         with:
-          node-version: 12.x
-      - name: npm ci
+          node-version: 17.3.1
+
+      - name: Install packages
         run: |
           npm ci
-      - name: run build
-        run: npm run build-nextjs
-      - name: run Lighthouse CI
+
+      - name: Build
+        run: |
+          npm run build
+
+      - name: Run Lighthouse CI
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
-          npm install -g @lhci/cli@0.3.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          npm install -g @lhci/cli
+          lhci autorun || echo "Fail to Run Lighthouse CI!"
